CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    age INTEGER,
    sex TEXT,
    goals TEXT,
    dailydiary_api_key TEXT,
    dreamdiary_api_key TEXT,
    chatgpt_daily_diary_coachname TEXT,
    chatgpt_dream_diary_coachname TEXT,
    display_name TEXT,
    pronouns TEXT,
    timezone TEXT DEFAULT 'UTC',
    ai_tone TEXT DEFAULT 'friendly',
    ai_verbosity TEXT DEFAULT 'balanced',
    ai_focus TEXT DEFAULT 'reflective',
    allow_ai_history INTEGER DEFAULT 1,
    allow_ai_attachment_context INTEGER DEFAULT 1,
    ai_model TEXT DEFAULT 'gpt-4.1-mini',
    gender TEXT,
    custom_guidance TEXT,
    holiday_country_code TEXT,
    show_public_holidays INTEGER DEFAULT 0,
    profile_picture_storage_key TEXT,
    show_on_this_day INTEGER DEFAULT 0,
    writing_reminders_enabled INTEGER DEFAULT 0,
    writing_reminder_days TEXT,
    writing_reminder_time TEXT DEFAULT '19:00',
    writing_reminder_silence_days INTEGER DEFAULT 3,
    writing_reminder_entry_types TEXT DEFAULT 'daily,dream',
    writing_rhythm_progress_enabled INTEGER DEFAULT 0,
    writing_rhythm_weekly_goal INTEGER DEFAULT 4,
    chat_enabled INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    daily_diary_prompt TEXT,
    dream_diary_prompt TEXT
);

CREATE TABLE IF NOT EXISTS dailydiary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    entry_date DATE,
    entry_number INTEGER,
    user_message TEXT,
    ai_response TEXT,
    daily_people_names TEXT,
    tags TEXT,
    title TEXT,
    daily_places TEXT,
    import_date TIMESTAMPTZ,
    imported INTEGER DEFAULT 0,
    mood TEXT,
    ai_style TEXT,
    content_hash TEXT,
    image_url TEXT,
    image_storage_key TEXT,
    image_position_x DOUBLE PRECISION DEFAULT 50,
    image_position_y DOUBLE PRECISION DEFAULT 50,
    image_prompt TEXT,
    recycled_image_prompt TEXT,
    entry_time TEXT,
    image_source TEXT,
    analysis_attachment_refs TEXT,
    import_id BIGINT
);

CREATE TABLE IF NOT EXISTS dreamdiary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    entry_date DATE,
    entry_number INTEGER,
    title TEXT,
    "cast" TEXT,
    location TEXT,
    period TEXT,
    emotion TEXT,
    plot TEXT,
    symbols_and_imagery TEXT,
    insight TEXT,
    action TEXT,
    other TEXT,
    summary TEXT,
    interpretation TEXT,
    image_prompt TEXT,
    image_url TEXT,
    dream_people_names TEXT,
    tags TEXT,
    dream_places TEXT,
    import_date TIMESTAMPTZ,
    imported INTEGER DEFAULT 0,
    mood TEXT,
    ai_style TEXT,
    content_hash TEXT,
    recycled_image_prompt TEXT,
    image_storage_key TEXT,
    image_position_x DOUBLE PRECISION DEFAULT 50,
    image_position_y DOUBLE PRECISION DEFAULT 50,
    entry_time TEXT,
    image_source TEXT,
    analysis_attachment_refs TEXT,
    import_id BIGINT
);

CREATE TABLE IF NOT EXISTS import_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    filename TEXT NOT NULL,
    entries_imported INTEGER DEFAULT 0,
    entries_skipped INTEGER DEFAULT 0,
    file_size INTEGER,
    imported_at TEXT,
    file_size_bytes INTEGER NOT NULL DEFAULT 0,
    inserted_daily INTEGER NOT NULL DEFAULT 0,
    skipped_daily INTEGER NOT NULL DEFAULT 0,
    inserted_dreams INTEGER NOT NULL DEFAULT 0,
    skipped_dreams INTEGER NOT NULL DEFAULT 0,
    warnings TEXT,
    status TEXT NOT NULL DEFAULT 'success',
    duplicate_dates_json TEXT
);

CREATE TABLE IF NOT EXISTS export_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    exported_at TEXT NOT NULL,
    filename TEXT NOT NULL,
    from_date TEXT,
    to_date TEXT,
    include_daily INTEGER NOT NULL DEFAULT 1,
    include_dreams INTEGER NOT NULL DEFAULT 1,
    daily_count INTEGER NOT NULL DEFAULT 0,
    dream_count INTEGER NOT NULL DEFAULT 0,
    is_full_range INTEGER NOT NULL DEFAULT 0,
    guard_token TEXT,
    used_for_bulk_delete INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS import_sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    filename TEXT NOT NULL,
    file_size_bytes INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    consumed_at TEXT
);

CREATE TABLE IF NOT EXISTS import_jobs (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    import_session_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    processed INTEGER NOT NULL DEFAULT 0,
    total INTEGER NOT NULL DEFAULT 0,
    percent INTEGER NOT NULL DEFAULT 0,
    message TEXT NOT NULL DEFAULT '',
    error TEXT,
    request_json TEXT NOT NULL DEFAULT '{}',
    result_json TEXT,
    import_id BIGINT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    worker_token TEXT,
    lease_expires_at TEXT
);

CREATE TABLE IF NOT EXISTS entry_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    entry_type TEXT NOT NULL,
    entry_id BIGINT NOT NULL,
    asset_role TEXT NOT NULL DEFAULT 'attachment',
    storage_key TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size_bytes INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    derived_text TEXT,
    derived_text_source TEXT,
    derived_text_updated_at TEXT
);

CREATE TABLE IF NOT EXISTS important_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    label TEXT NOT NULL,
    starts_on TEXT,
    month INTEGER NOT NULL,
    day INTEGER NOT NULL,
    original_year INTEGER,
    category TEXT NOT NULL DEFAULT 'other',
    recurrence TEXT NOT NULL DEFAULT 'yearly',
    icon_name TEXT NOT NULL DEFAULT 'event',
    accent_color TEXT NOT NULL DEFAULT 'amber',
    ends_on TEXT,
    linked_entry_refs TEXT,
    image_url TEXT,
    image_storage_key TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public_holiday_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code TEXT NOT NULL,
    holiday_year INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(country_code, holiday_year)
);

CREATE TABLE IF NOT EXISTS entry_resurfacing_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    entry_type TEXT NOT NULL CHECK(entry_type IN ('daily', 'dream', 'thought_record')),
    entry_id BIGINT NOT NULL,
    hidden_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, entry_type, entry_id)
);

CREATE TABLE IF NOT EXISTS reflection_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period_type TEXT NOT NULL CHECK(period_type IN ('weekly', 'monthly')),
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    title TEXT NOT NULL,
    summary_text TEXT NOT NULL,
    themes_json TEXT NOT NULL DEFAULT '[]',
    source_refs_json TEXT NOT NULL DEFAULT '[]',
    model TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, period_type, period_start)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL,
    request_id TEXT,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_observability_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    conversation_id TEXT,
    request_id TEXT,
    event_type TEXT NOT NULL,
    error_code TEXT,
    latency_ms INTEGER,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    model TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cbt_worksheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    worksheet_type TEXT NOT NULL DEFAULT 'thought_record'
        CHECK(worksheet_type IN ('thought_record')),
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'completed')),
    current_step INTEGER NOT NULL DEFAULT 1 CHECK(current_step BETWEEN 1 AND 7),
    record_date TEXT NOT NULL DEFAULT CURRENT_DATE,
    linked_entry_type TEXT CHECK(linked_entry_type IN ('daily', 'dream')),
    linked_entry_id BIGINT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,
    CHECK(
        (linked_entry_type IS NULL AND linked_entry_id IS NULL) OR
        (linked_entry_type IS NOT NULL AND linked_entry_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS cbt_thought_record_data (
    worksheet_id BIGINT PRIMARY KEY REFERENCES cbt_worksheets(id) ON DELETE CASCADE,
    situation TEXT NOT NULL DEFAULT '',
    feelings_before_json TEXT NOT NULL DEFAULT '[]',
    unhelpful_thoughts TEXT NOT NULL DEFAULT '',
    evidence_for TEXT NOT NULL DEFAULT '',
    evidence_against TEXT NOT NULL DEFAULT '',
    balanced_thought TEXT NOT NULL DEFAULT '',
    feelings_after_json TEXT NOT NULL DEFAULT '[]',
    next_step TEXT NOT NULL DEFAULT '',
    ai_response TEXT NOT NULL DEFAULT '',
    ai_responded_at TEXT,
    ai_response_outdated INTEGER NOT NULL DEFAULT 0 CHECK(ai_response_outdated IN (0, 1))
);

CREATE TABLE IF NOT EXISTS entry_ai_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode TEXT NOT NULL,
    reference_date DATE,
    summary_header TEXT,
    tags TEXT,
    people_names TEXT,
    places TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_entries_user_date
ON dailydiary_entries(user_id, entry_date, entry_number, id);

CREATE INDEX IF NOT EXISTS idx_dream_entries_user_date
ON dreamdiary_entries(user_id, entry_date, entry_number, id);

CREATE INDEX IF NOT EXISTS idx_entry_assets_lookup
ON entry_assets(user_id, entry_type, entry_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_import_jobs_user_status
ON import_jobs(user_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_important_days_user_lookup
ON important_days(user_id, month, day);

CREATE INDEX IF NOT EXISTS idx_entry_resurfacing_user_lookup
ON entry_resurfacing_preferences(user_id, entry_type, entry_id);

CREATE INDEX IF NOT EXISTS idx_reflection_summaries_user_period
ON reflection_summaries(user_id, period_type, period_start DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation
ON chat_messages(user_id, conversation_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_created
ON chat_messages(user_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_messages_request_role
ON chat_messages(user_id, request_id, role)
WHERE request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chat_observability_user_created
ON chat_observability_events(user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_chat_observability_event_created
ON chat_observability_events(event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cbt_worksheets_user_status
ON cbt_worksheets(user_id, status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_cbt_worksheets_linked_entry
ON cbt_worksheets(user_id, linked_entry_type, linked_entry_id)
WHERE linked_entry_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cbt_worksheets_user_date
ON cbt_worksheets(user_id, record_date, id);

INSERT INTO schema_migrations(version)
VALUES ('0001_initial_schema')
ON CONFLICT (version) DO NOTHING;
