CREATE TABLE IF NOT EXISTS billing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier TEXT NOT NULL UNIQUE
        CHECK(tier IN ('free', 'personal', 'plus', 'therapeutic', 'lifetime', 'complimentary', 'administrator')),
    public_name TEXT NOT NULL,
    strapline TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    monthly_price_gbp_pence INTEGER NOT NULL DEFAULT 0,
    annual_price_gbp_pence INTEGER NOT NULL DEFAULT 0,
    annual_discount_percent INTEGER NOT NULL DEFAULT 0,
    quotas_json TEXT NOT NULL DEFAULT '{}',
    features_json TEXT NOT NULL DEFAULT '[]',
    gated_features_json TEXT NOT NULL DEFAULT '[]',
    is_paid INTEGER NOT NULL DEFAULT 0 CHECK(is_paid IN (0, 1)),
    is_public INTEGER NOT NULL DEFAULT 1 CHECK(is_public IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    catalogue_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_billing_plans_public_order
ON billing_plans(is_public, sort_order);
