CREATE TABLE IF NOT EXISTS admin_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info'
        CHECK(severity IN ('info', 'success', 'warning', 'critical')),
    placement TEXT NOT NULL DEFAULT 'banner'
        CHECK(placement IN ('banner', 'bell', 'both')),
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK(status IN ('draft', 'published', 'archived')),
    starts_at TEXT,
    ends_at TEXT,
    timezone TEXT NOT NULL DEFAULT 'Europe/London',
    dismissible INTEGER NOT NULL DEFAULT 1 CHECK(dismissible IN (0, 1)),
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_announcement_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL REFERENCES admin_announcements(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL CHECK(target_type IN ('all', 'tier', 'user')),
    target_value TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_announcement_user_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL REFERENCES admin_announcements(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at TEXT,
    dismissed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(announcement_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_announcements_status_dates
ON admin_announcements(status, starts_at, ends_at);

CREATE INDEX IF NOT EXISTS idx_admin_announcement_targets_lookup
ON admin_announcement_targets(announcement_id, target_type, target_value);

CREATE INDEX IF NOT EXISTS idx_admin_announcement_state_user
ON admin_announcement_user_state(user_id, dismissed_at, read_at);
