CREATE TABLE IF NOT EXISTS admin_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    target_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    outcome TEXT NOT NULL DEFAULT 'success'
        CHECK(outcome IN ('success', 'failure')),
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_created
ON admin_audit_events(created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_actor
ON admin_audit_events(actor_user_id, created_at DESC);

INSERT INTO schema_migrations(version)
VALUES ('0006_admin_audit_events')
ON CONFLICT (version) DO NOTHING;
