"""Data-driven subscription plan catalogue for OpenMynd.

The internal tier keys stay stable for entitlements and Stripe metadata. Public names,
prices, copy, and quotas are read from this table so an administrator can adjust the
matrix without code changes.
"""

from __future__ import annotations

import json
from copy import deepcopy
from typing import Any

from services.billing_entitlements import VALID_TIERS
from services.database import POSTGRES_PROVIDER, SQLITE_PROVIDER


PLAN_CATALOGUE_VERSION = 2
AI_ANALYSIS_LIMIT_KEY = "ai_analysis_monthly"


def _provider(conn) -> str:
    return getattr(conn, "database_provider", SQLITE_PROVIDER)


def ensure_plan_catalogue_table(conn) -> None:
    """Create the editable plan catalogue table when a database is behind migrations."""
    provider = _provider(conn)
    id_definition = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if provider == POSTGRES_PROVIDER
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS billing_plans (
            id {id_definition},
            tier TEXT NOT NULL UNIQUE
                CHECK(tier IN ('free', 'personal', 'plus', 'therapeutic', 'lifetime', 'complimentary', 'administrator')),
            public_name TEXT NOT NULL,
            strapline TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            monthly_price_gbp_pence INTEGER NOT NULL DEFAULT 0,
            annual_price_gbp_pence INTEGER NOT NULL DEFAULT 0,
            annual_discount_percent INTEGER NOT NULL DEFAULT 0,
            quotas_json TEXT NOT NULL DEFAULT '{{}}',
            features_json TEXT NOT NULL DEFAULT '[]',
            gated_features_json TEXT NOT NULL DEFAULT '[]',
            is_paid INTEGER NOT NULL DEFAULT 0 CHECK(is_paid IN (0, 1)),
            is_public INTEGER NOT NULL DEFAULT 1 CHECK(is_public IN (0, 1)),
            sort_order INTEGER NOT NULL DEFAULT 0,
            catalogue_version INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_billing_plans_public_order
        ON billing_plans(is_public, sort_order)
        """
    )


DEFAULT_PLAN_CATALOGUE: list[dict[str, Any]] = [
    {
        "tier": "free",
        "public_name": "Free",
        "strapline": "Start journalling privately.",
        "description": "Basic journalling tools with a small AI allowance.",
        "monthly_price_gbp_pence": 0,
        "annual_price_gbp_pence": 0,
        "annual_discount_percent": 0,
        "is_paid": False,
        "is_public": True,
        "sort_order": 10,
        "quotas": {
            "storage_mb": 250,
            AI_ANALYSIS_LIMIT_KEY: 10,
            "ai_chat_monthly": 10,
            "ai_images_monthly": 0,
            "ocr_pages_monthly": 5,
            "transcription_minutes_monthly": 0,
        },
        "features": [
            "Private diary, dream, and calendar entries",
            "Dashboard, search, and export tools",
            "10 AI responses per month",
            "250 MB media storage",
        ],
        "gated_features": ["ai_images", "audio_transcription", "large_media_storage"],
    },
    {
        "tier": "personal",
        "public_name": "Plus",
        "strapline": "Regular AI-supported reflection.",
        "description": "Higher AI and media limits for consistent personal use.",
        "monthly_price_gbp_pence": 499,
        "annual_price_gbp_pence": 4790,
        "annual_discount_percent": 20,
        "is_paid": True,
        "is_public": True,
        "sort_order": 20,
        "quotas": {
            "storage_mb": 2048,
            AI_ANALYSIS_LIMIT_KEY: 250,
            "ai_chat_monthly": 150,
            "ai_images_monthly": 10,
            "ocr_pages_monthly": 100,
            "transcription_minutes_monthly": 30,
        },
        "features": [
            "Everything in Free",
            "250 AI responses per month",
            "AI image generation for entries",
            "OCR and audio transcription allowance",
            "2 GB media storage",
        ],
        "gated_features": [],
    },
    {
        "tier": "plus",
        "public_name": "Premier",
        "strapline": "Maximum headroom for power users.",
        "description": "More AI, media, and response capacity for deeper use.",
        "monthly_price_gbp_pence": 1199,
        "annual_price_gbp_pence": 11510,
        "annual_discount_percent": 20,
        "is_paid": True,
        "is_public": True,
        "sort_order": 30,
        "quotas": {
            "storage_mb": 10240,
            AI_ANALYSIS_LIMIT_KEY: 1000,
            "ai_chat_monthly": 600,
            "ai_images_monthly": 40,
            "ocr_pages_monthly": 500,
            "transcription_minutes_monthly": 180,
        },
        "features": [
            "Everything in Plus",
            "1,000 AI responses per month",
            "Higher chat, image, OCR, and transcription limits",
            "Priority headroom for heavier imports",
            "10 GB media storage",
        ],
        "gated_features": [],
    },
    {
        "tier": "complimentary",
        "public_name": "Complimentary",
        "strapline": "Owner-granted access.",
        "description": "Manual access for testing, support, or selected users.",
        "monthly_price_gbp_pence": 0,
        "annual_price_gbp_pence": 0,
        "annual_discount_percent": 0,
        "is_paid": False,
        "is_public": False,
        "sort_order": 80,
        "quotas": {
            "storage_mb": 10240,
            AI_ANALYSIS_LIMIT_KEY: 1000,
            "ai_chat_monthly": 600,
            "ai_images_monthly": 40,
            "ocr_pages_monthly": 500,
            "transcription_minutes_monthly": 180,
        },
        "features": ["Manual owner-granted access matching Premier capacity"],
        "gated_features": [],
    },
    {
        "tier": "lifetime",
        "public_name": "Lifetime",
        "strapline": "Permanent owner-granted access.",
        "description": "Permanent entitlement not tied to a recurring subscription.",
        "monthly_price_gbp_pence": 0,
        "annual_price_gbp_pence": 0,
        "annual_discount_percent": 0,
        "is_paid": False,
        "is_public": False,
        "sort_order": 90,
        "quotas": {
            "storage_mb": 10240,
            AI_ANALYSIS_LIMIT_KEY: 1000,
            "ai_chat_monthly": 600,
            "ai_images_monthly": 40,
            "ocr_pages_monthly": 500,
            "transcription_minutes_monthly": 180,
        },
        "features": ["Permanent access matching Premier capacity"],
        "gated_features": [],
    },
    {
        "tier": "administrator",
        "public_name": "Administrator",
        "strapline": "Owner operations access.",
        "description": "Unlimited owner access for administration and testing.",
        "monthly_price_gbp_pence": 0,
        "annual_price_gbp_pence": 0,
        "annual_discount_percent": 0,
        "is_paid": False,
        "is_public": False,
        "sort_order": 100,
        "quotas": {
            "storage_mb": None,
            AI_ANALYSIS_LIMIT_KEY: None,
            "ai_chat_monthly": None,
            "ai_images_monthly": None,
            "ocr_pages_monthly": None,
            "transcription_minutes_monthly": None,
        },
        "features": ["Unlimited owner access"],
        "gated_features": [],
    },
]


def default_plan_for_tier(tier: str) -> dict[str, Any]:
    normalized = _validate_tier(tier)
    for plan in DEFAULT_PLAN_CATALOGUE:
        if plan["tier"] == normalized:
            return deepcopy(plan)
    raise ValueError(f"Unsupported tier: {tier}")


def seed_default_plan_catalogue(conn) -> None:
    ensure_plan_catalogue_table(conn)
    for plan in DEFAULT_PLAN_CATALOGUE:
        conn.execute(
            """
            INSERT INTO billing_plans (
                tier,
                public_name,
                strapline,
                description,
                monthly_price_gbp_pence,
                annual_price_gbp_pence,
                annual_discount_percent,
                quotas_json,
                features_json,
                gated_features_json,
                is_paid,
                is_public,
                sort_order,
                catalogue_version
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(tier) DO NOTHING
            """,
            _plan_row_values(plan),
        )
        if plan["tier"] in {"free", "personal", "plus"}:
            conn.execute(
                """
                UPDATE billing_plans
                SET
                    strapline = ?,
                    description = ?,
                    features_json = ?,
                    catalogue_version = ?,
                    updated_at = CURRENT_TIMESTAMP
                WHERE tier = ?
                  AND catalogue_version < ?
                """,
                (
                    plan["strapline"],
                    plan["description"],
                    json.dumps(plan["features"]),
                    PLAN_CATALOGUE_VERSION,
                    plan["tier"],
                    PLAN_CATALOGUE_VERSION,
                ),
            )
    conn.execute(
        """
        UPDATE billing_plans
        SET
            features_json = REPLACE(
                REPLACE(
                    REPLACE(features_json, 'AI analyses', 'AI responses'),
                    'heavier imports and analysis',
                    'heavier imports and AI use'
                ),
                'analysis capacity',
                'response capacity'
            ),
            description = REPLACE(description, 'analysis capacity', 'response capacity'),
            catalogue_version = ?
        WHERE features_json LIKE '%AI analyses%'
           OR features_json LIKE '%heavier imports and analysis%'
           OR description LIKE '%analysis capacity%'
        """,
        (PLAN_CATALOGUE_VERSION,),
    )


def list_plan_catalogue(conn, *, include_internal: bool = False) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT tier, public_name, strapline, description, monthly_price_gbp_pence,
               annual_price_gbp_pence, annual_discount_percent, quotas_json,
               features_json, gated_features_json, is_paid, is_public, sort_order,
               catalogue_version, updated_at
        FROM billing_plans
        WHERE (? = 1 OR is_public = 1)
        ORDER BY sort_order ASC, id ASC
        """,
        (1 if include_internal else 0,),
    ).fetchall()
    if not rows:
        seed_default_plan_catalogue(conn)
        rows = conn.execute(
            """
            SELECT tier, public_name, strapline, description, monthly_price_gbp_pence,
                   annual_price_gbp_pence, annual_discount_percent, quotas_json,
                   features_json, gated_features_json, is_paid, is_public, sort_order,
                   catalogue_version, updated_at
            FROM billing_plans
            WHERE (? = 1 OR is_public = 1)
            ORDER BY sort_order ASC, id ASC
            """,
            (1 if include_internal else 0,),
        ).fetchall()
    return [_serialise_plan(row) for row in rows]


def get_plan(conn, tier: str) -> dict[str, Any]:
    normalized = _validate_tier(tier)
    row = conn.execute(
        """
        SELECT tier, public_name, strapline, description, monthly_price_gbp_pence,
               annual_price_gbp_pence, annual_discount_percent, quotas_json,
               features_json, gated_features_json, is_paid, is_public, sort_order,
               catalogue_version, updated_at
        FROM billing_plans
        WHERE tier = ?
        """,
        (normalized,),
    ).fetchone()
    if row is None:
        seed_default_plan_catalogue(conn)
        row = conn.execute(
            """
            SELECT tier, public_name, strapline, description, monthly_price_gbp_pence,
                   annual_price_gbp_pence, annual_discount_percent, quotas_json,
                   features_json, gated_features_json, is_paid, is_public, sort_order,
                   catalogue_version, updated_at
            FROM billing_plans
            WHERE tier = ?
            """,
            (normalized,),
        ).fetchone()
    if row is None:
        return default_plan_for_tier(normalized)
    return _serialise_plan(row)


def upsert_plan(conn, payload: dict[str, Any]) -> dict[str, Any]:
    tier = _validate_tier(str(payload.get("tier") or ""))
    current = get_plan(conn, tier)
    merged = {
        **current,
        **{
            key: payload[key]
            for key in (
                "public_name",
                "strapline",
                "description",
                "monthly_price_gbp_pence",
                "annual_price_gbp_pence",
                "annual_discount_percent",
                "quotas",
                "features",
                "gated_features",
                "is_paid",
                "is_public",
                "sort_order",
            )
            if key in payload
        },
    }
    if isinstance(payload.get("quotas"), dict):
        merged["quotas"] = {**(current.get("quotas") or {}), **payload["quotas"]}
    sanitized = _sanitize_plan(merged)
    conn.execute(
        """
        INSERT INTO billing_plans (
            tier,
            public_name,
            strapline,
            description,
            monthly_price_gbp_pence,
            annual_price_gbp_pence,
            annual_discount_percent,
            quotas_json,
            features_json,
            gated_features_json,
            is_paid,
            is_public,
            sort_order,
            catalogue_version
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(tier) DO UPDATE SET
            public_name = excluded.public_name,
            strapline = excluded.strapline,
            description = excluded.description,
            monthly_price_gbp_pence = excluded.monthly_price_gbp_pence,
            annual_price_gbp_pence = excluded.annual_price_gbp_pence,
            annual_discount_percent = excluded.annual_discount_percent,
            quotas_json = excluded.quotas_json,
            features_json = excluded.features_json,
            gated_features_json = excluded.gated_features_json,
            is_paid = excluded.is_paid,
            is_public = excluded.is_public,
            sort_order = excluded.sort_order,
            catalogue_version = excluded.catalogue_version,
            updated_at = CURRENT_TIMESTAMP
        """,
        _plan_row_values(sanitized),
    )
    return get_plan(conn, tier)


def _plan_row_values(plan: dict[str, Any]) -> tuple[Any, ...]:
    sanitized = _sanitize_plan(plan)
    return (
        sanitized["tier"],
        sanitized["public_name"],
        sanitized["strapline"],
        sanitized["description"],
        sanitized["monthly_price_gbp_pence"],
        sanitized["annual_price_gbp_pence"],
        sanitized["annual_discount_percent"],
        json.dumps(sanitized["quotas"], ensure_ascii=False, sort_keys=True),
        json.dumps(sanitized["features"], ensure_ascii=False),
        json.dumps(sanitized["gated_features"], ensure_ascii=False),
        1 if sanitized["is_paid"] else 0,
        1 if sanitized["is_public"] else 0,
        sanitized["sort_order"],
        PLAN_CATALOGUE_VERSION,
    )


def _sanitize_plan(plan: dict[str, Any]) -> dict[str, Any]:
    tier = _validate_tier(str(plan.get("tier") or ""))
    public_name = _clean_text(plan.get("public_name"), fallback=tier.title(), max_length=40)
    strapline = _clean_text(plan.get("strapline"), fallback="", max_length=90)
    description = _clean_text(plan.get("description"), fallback="", max_length=180)
    quotas = _sanitize_quotas(plan.get("quotas") if isinstance(plan.get("quotas"), dict) else {})
    features = _sanitize_string_list(plan.get("features"), max_items=12, max_length=120)
    gated_features = _sanitize_string_list(
        plan.get("gated_features"),
        max_items=20,
        max_length=60,
    )
    return {
        "tier": tier,
        "public_name": public_name,
        "strapline": strapline,
        "description": description,
        "monthly_price_gbp_pence": _bounded_int(plan.get("monthly_price_gbp_pence"), 0, 100000),
        "annual_price_gbp_pence": _bounded_int(plan.get("annual_price_gbp_pence"), 0, 1000000),
        "annual_discount_percent": _bounded_int(plan.get("annual_discount_percent"), 0, 80),
        "quotas": quotas,
        "features": features,
        "gated_features": gated_features,
        "is_paid": bool(plan.get("is_paid")),
        "is_public": bool(plan.get("is_public")),
        "sort_order": _bounded_int(plan.get("sort_order"), 0, 1000),
    }


def _sanitize_quotas(raw_quotas: dict[str, Any]) -> dict[str, int | None]:
    default = default_plan_for_tier("free")["quotas"]
    merged = {**default, **raw_quotas}
    sanitized: dict[str, int | None] = {}
    for key, value in merged.items():
        normalized_key = str(key or "").strip().lower()
        if not normalized_key or not normalized_key.replace("_", "").isalnum():
            continue
        if value is None:
            sanitized[normalized_key] = None
            continue
        sanitized[normalized_key] = _bounded_int(value, 0, 1000000)
    return sanitized


def _serialise_plan(row: Any) -> dict[str, Any]:
    quotas = _decode_json(_row_get(row, "quotas_json"), fallback={})
    features = _decode_json(_row_get(row, "features_json"), fallback=[])
    gated_features = _decode_json(_row_get(row, "gated_features_json"), fallback=[])
    return {
        "tier": str(_row_get(row, "tier") or "free"),
        "public_name": str(_row_get(row, "public_name") or "Free"),
        "strapline": str(_row_get(row, "strapline") or ""),
        "description": str(_row_get(row, "description") or ""),
        "monthly_price_gbp_pence": int(_row_get(row, "monthly_price_gbp_pence") or 0),
        "annual_price_gbp_pence": int(_row_get(row, "annual_price_gbp_pence") or 0),
        "annual_discount_percent": int(_row_get(row, "annual_discount_percent") or 0),
        "quotas": quotas if isinstance(quotas, dict) else {},
        "features": features if isinstance(features, list) else [],
        "gated_features": gated_features if isinstance(gated_features, list) else [],
        "is_paid": bool(_row_get(row, "is_paid")),
        "is_public": bool(_row_get(row, "is_public")),
        "sort_order": int(_row_get(row, "sort_order") or 0),
        "catalogue_version": int(_row_get(row, "catalogue_version") or PLAN_CATALOGUE_VERSION),
        "updated_at": _row_get(row, "updated_at"),
    }


def _decode_json(value: Any, *, fallback: Any) -> Any:
    if value in {None, ""}:
        return deepcopy(fallback)
    try:
        return json.loads(str(value))
    except (TypeError, ValueError, json.JSONDecodeError):
        return deepcopy(fallback)


def _validate_tier(tier: str) -> str:
    normalized = (tier or "").strip().lower()
    if normalized not in VALID_TIERS:
        raise ValueError(f"Unsupported tier: {tier}")
    return normalized


def _clean_text(value: Any, *, fallback: str, max_length: int) -> str:
    text = " ".join(str(value or "").split()).strip()
    if not text:
        return fallback
    return text[:max_length]


def _bounded_int(value: Any, minimum: int, maximum: int) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        parsed = minimum
    return max(minimum, min(maximum, parsed))


def _sanitize_string_list(value: Any, *, max_items: int, max_length: int) -> list[str]:
    if not isinstance(value, list):
        return []
    cleaned: list[str] = []
    for item in value:
        text = _clean_text(item, fallback="", max_length=max_length)
        if text:
            cleaned.append(text)
        if len(cleaned) >= max_items:
            break
    return cleaned


def _row_get(row: Any, key: str) -> Any:
    if row is None:
        return None
    if isinstance(row, dict):
        return row.get(key)
    try:
        return row[key]
    except (KeyError, TypeError, IndexError):
        return getattr(row, key, None)
